/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IData = t.array("IProject");

const exportedTypeSuite: t.ITypeSuite = {
  IData,
};
export default exportedTypeSuite;
