/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IProjects = t.array("IProject");

export const IProjectsData = t.array("IProjectData");

const exportedTypeSuite: t.ITypeSuite = {
  IProjects,
  IProjectsData,
};
export default exportedTypeSuite;
