/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ITicketType = t.enumtype({
  "Feature": "feature",
  "Fix": "fix",
});

const exportedTypeSuite: t.ITypeSuite = {
  ITicketType,
};
export default exportedTypeSuite;
