/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ITicketLinkData = t.iface([], {
  tooltip: "string",
  url: "string",
});

export const ITicketLink = t.iface(["ITicketLinkData"], {
  id: "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  ITicketLinkData,
  ITicketLink,
};
export default exportedTypeSuite;
