/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ITicketData = t.iface([], {
  type: "ITicketType",
  code: "string",
  name: "string",
  url: t.opt("string"),
  hidden: "boolean",
  links: t.array("ITicketLinkData"),
});

export const ITicket = t.iface(["ITicketData"], {
  id: "string",
  links: t.array("ITicketLink"),
});

const exportedTypeSuite: t.ITypeSuite = {
  ITicketData,
  ITicket,
};
export default exportedTypeSuite;
