/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ITicket = t.iface([], {
  "type": "ITicketType",
  "code": "string",
  "name": "string",
  "url": t.opt("string"),
  "hidden": "boolean",
  "links": t.array("ITicketLink"),
});

const exportedTypeSuite: t.ITypeSuite = {
  ITicket,
};
export default exportedTypeSuite;
